# Generated by Django 3.0.6 on 2020-10-31 19:10

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('position', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(default='test.png', upload_to='partners')),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(default='test.png', upload_to='partners')),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
