# Generated by Django 3.0.6 on 2020-11-16 17:26

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='href_url',
            field=models.URLField(blank=True, default='', help_text='Add here any site reference.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_detail',
            field=imagekit.models.fields.ProcessedImageField(default='test.png', help_text='Second Image for Detail view', upload_to='news'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='test.png', help_text='Presentation Image', upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
