# Generated by Django 3.0.6 on 2020-11-25 15:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201116_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_detail',
            field=imagekit.models.fields.ProcessedImageField(default='test.png', help_text='Second Image for Detail view', upload_to='events'),
        ),
    ]
