# Generated by Django 3.0.6 on 2020-10-31 19:10

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201021_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='test.png', upload_to='news'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='slug-like-that'),
        ),
    ]
