# Generated by Django 3.0.6 on 2020-11-16 15:39

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201031_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image_detail',
            field=imagekit.models.fields.ProcessedImageField(default='test.png', upload_to='news'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
