# Generated by Django 3.0.6 on 2020-11-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_new_href_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='href_url',
            field=models.URLField(default='', help_text='Add here any site reference.', null=True),
        ),
    ]
