# Generated by Django 3.0.6 on 2020-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201116_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='href_url',
            field=models.URLField(blank=True, default='', help_text='Add here any site reference.', null=True),
        ),
    ]
