# Generated by Django 3.0.6 on 2020-10-20 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name given', max_length=128)),
                ('surname', models.CharField(default='No surname given', max_length=128)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
                ('member_pic', models.ImageField(blank=True, default='media/members/members_pic/default_profile_pic.jpg', null=True, upload_to='media/members/members_pic')),
                ('role', models.CharField(choices=[('P', 'President'), ('VP', 'Vice-President'), ('SG', 'Secretary General'), ('TR', 'Treasurer'), ('AL', 'Alternate')], default='AL', max_length=2)),
                ('social_url', models.URLField(default='www')),
                ('member_bio', models.TextField(default='(will be public)', max_length='500', verbose_name='Experiences')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(default='No name given', max_length=128)),
                ('surname', models.CharField(default='No surname given', max_length=128)),
                ('birth_date', models.DateTimeField(verbose_name='birth day')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
                ('education_background', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('GR', 'Graduate'), ('OT', 'Other')], default='OT', max_length=2)),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Deadline', 'Deadline'), ('Late', 'Late')], default='Not Paid', max_length=100)),
                ('phone', models.CharField(default='No phone given', max_length=128)),
                ('init_date', models.DateTimeField(verbose_name='date created')),
                ('last_payment_date', models.DateTimeField(verbose_name='date paid')),
                ('mun_exp_bio', models.TextField(default='No bio given.', max_length=500, verbose_name='Experience')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMember',
            fields=[
                ('name', models.CharField(default='No name given', max_length=128)),
                ('surname', models.CharField(default='No surname given', max_length=128)),
                ('birth_date', models.DateTimeField(verbose_name='birth day')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('mail', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
                ('education_background', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('GR', 'Graduate'), ('OT', 'Other')], default='OT', max_length=2)),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Deadline', 'Deadline'), ('Late', 'Late')], default='Not Paid', max_length=100)),
                ('phone', models.CharField(default='No phone given', max_length=128)),
                ('init_date', models.DateTimeField(verbose_name='date created')),
                ('last_payment_date', models.DateTimeField(verbose_name='date paid')),
                ('mun_exp_bio', models.TextField(default='No bio given.', max_length=500, verbose_name='Experience')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical member',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBoardMember',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='No name given', max_length=128)),
                ('surname', models.CharField(default='No surname given', max_length=128)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
                ('member_pic', models.TextField(blank=True, default='media/members/members_pic/default_profile_pic.jpg', max_length=100, null=True)),
                ('role', models.CharField(choices=[('P', 'President'), ('VP', 'Vice-President'), ('SG', 'Secretary General'), ('TR', 'Treasurer'), ('AL', 'Alternate')], default='AL', max_length=2)),
                ('social_url', models.URLField(default='www')),
                ('member_bio', models.TextField(default='(will be public)', max_length='500', verbose_name='Experiences')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical board member',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
