# Generated by Django 3.0.6 on 2020-11-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20201108_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='member_bio',
            field=models.TextField(default='(will be public)', max_length='1000', verbose_name='Experiences'),
        ),
        migrations.AlterField(
            model_name='historicalboardmember',
            name='member_bio',
            field=models.TextField(default='(will be public)', max_length='1000', verbose_name='Experiences'),
        ),
    ]
