# Generated by Django 3.0.6 on 2020-11-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20201114_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='email_url',
            field=models.EmailField(default='', help_text='Test', max_length=254),
        ),
        migrations.AddField(
            model_name='historicalboardmember',
            name='email_url',
            field=models.EmailField(default='', help_text='Test', max_length=254),
        ),
    ]
