# Generated by Django 3.0.6 on 2020-11-20 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_auto_20201115_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateMember',
            fields=[
                ('name', models.CharField(default='No name given', max_length=128)),
                ('surname', models.CharField(default='No surname given', max_length=128)),
                ('birth_date', models.DateTimeField(verbose_name='birth day')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
                ('education_background', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('GR', 'Graduate'), ('OT', 'Other')], default='OT', max_length=2)),
                ('phone', models.CharField(default='No phone given', max_length=128)),
                ('init_date', models.DateTimeField(verbose_name='date created')),
                ('mun_exp_bio', models.TextField(default='No bio given.', max_length=500, verbose_name='Experience')),
            ],
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='member_bio',
            field=models.TextField(default='(will be public)', max_length=2000, verbose_name='Experiences'),
        ),
        migrations.AlterField(
            model_name='historicalboardmember',
            name='member_bio',
            field=models.TextField(default='(will be public)', max_length=2000, verbose_name='Experiences'),
        ),
        migrations.CreateModel(
            name='HistoricalAssociateMember',
            fields=[
                ('name', models.CharField(default='No name given', max_length=128)),
                ('surname', models.CharField(default='No surname given', max_length=128)),
                ('birth_date', models.DateTimeField(verbose_name='birth day')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('mail', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2)),
                ('education_background', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('GR', 'Graduate'), ('OT', 'Other')], default='OT', max_length=2)),
                ('phone', models.CharField(default='No phone given', max_length=128)),
                ('init_date', models.DateTimeField(verbose_name='date created')),
                ('mun_exp_bio', models.TextField(default='No bio given.', max_length=500, verbose_name='Experience')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical associate member',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
